name: analysis_options_generator
description: A sample command-line application.
version: 3.0.0-alpha
repository: https://github.com/sunderee/analysis-options-generator

environment:
  sdk: ">=3.1.0"

dependencies:
  # HTML
  html: ^0.15.4

  # CLI arguments parser
  args: ^2.4.2

  # Utilities
  dart_scope_functions: ^0.1.0
  collection: ^1.18.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
