name: analysis_options_generator
description: A sample command-line application.
version: 3.0.0-alpha
repository: https://github.com/sunderee/analysis-options-generator

environment:
  sdk: ">=3.0.6"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
